var match=[
	{
		"schedule":"06-11",
		"screenings":[
			{
				id:'1',
				l_name:'法国',
				r_name:'罗马尼亚',
				l_img:'images/flag-1.png',
				r_img:'images/flag-2.png'
			},
			{
				id:'2',
				l_name:'阿尔巴尼亚',
				r_name:'瑞士',
				l_img:'images/flag-3.png',
				r_img:'images/flag-4.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-12",
		"screenings":[
			{
				id:'3',
				l_name:'威尔士',
				r_name:'斯洛伐克',
				l_img:'images/flag-5.png',
				r_img:'images/flag-6.png'
			},
			{
				id:'4',
				l_name:'英格兰',
				r_name:'俄罗斯',
				l_img:'images/flag-7.png',
				r_img:'images/flag-8.png'
			},
			{
				id:'5',
				l_name:'土耳其',
				r_name:'克罗地亚',
				l_img:'images/flag-9.png',
				r_img:'images/flag-10.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-13",
		"screenings":[
			{
				id:'6',
				l_name:'波兰',
				r_name:'北爱尔兰',
				l_img:'images/flag-11.png',
				r_img:'images/flag-12.png'
			},
			{
				id:'7',
				l_name:'德国',
				r_name:'乌克兰',
				l_img:'images/flag-13.png',
				r_img:'images/flag-14.png'
			},
			{
				id:'8',
				l_name:'西班牙',
				r_name:'捷克',
				l_img:'images/flag-15.png',
				r_img:'images/flag-16.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-14",
		"screenings":[
			{
				id:'9',
				l_name:'爱尔兰',
				r_name:'瑞典',
				l_img:'images/flag-17.png',
				r_img:'images/flag-18.png'
			},
			{
				id:'10',
				l_name:'比利时',
				r_name:'意大利',
				l_img:'images/flag-19.png',
				r_img:'images/flag-20.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-15",
		"screenings":[
			{
				id:'11',
				l_name:'奥地利',
				r_name:'匈牙利',
				l_img:'images/flag-21.png',
				r_img:'images/flag-22.png'
			},
			{
				id:'12',
				l_name:'葡萄牙',
				r_name:'冰岛',
				l_img:'images/flag-23.png',
				r_img:'images/flag-24.png'
			},
			{
				id:'13',
				l_name:'俄罗斯',
				r_name:'斯洛伐克',
				l_img:'images/flag-25.png',
				r_img:'images/flag-26.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-16",
		"screenings":[
			{
				id:'14',
				l_name:'罗马尼亚',
				r_name:'瑞士',
				l_img:'images/flag-27.png',
				r_img:'images/flag-28.png'
			},
			{
				id:'15',
				l_name:'法国',
				r_name:'阿尔巴尼亚',
				l_img:'images/flag-29.png',
				r_img:'images/flag-30.png'
			},
			{
				id:'16',
				l_name:'英格兰',
				r_name:'威尔士',
				l_img:'images/flag-31.png',
				r_img:'images/flag-32.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-17",
		"screenings":[
			{
				id:'17',
				l_name:'乌克兰',
				r_name:'北爱尔兰',
				l_img:'images/flag-33.png',
				r_img:'images/flag-34.png'
			},
			{
				id:'18',
				l_name:'德国',
				r_name:'波兰',
				l_img:'images/flag-35.png',
				r_img:'images/flag-36.png'
			},
			{
				id:'19',
				l_name:'意大利',
				r_name:'瑞典',
				l_img:'images/flag-37.png',
				r_img:'images/flag-38.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-18",
		"screenings":[
			{
				id:'20',
				l_name:'捷克',
				r_name:'克罗地亚',
				l_img:'images/flag-39.png',
				r_img:'images/flag-40.png'
			},
			{
				id:'21',
				l_name:'西班牙',
				r_name:'土耳其',
				l_img:'images/flag-41.png',
				r_img:'images/flag-42.png'
			},
			{
				id:'22',
				l_name:'比利时',
				r_name:'爱尔兰',
				l_img:'images/flag-43.png',
				r_img:'images/flag-44.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-19",
		"screenings":[
			{
				id:'23',
				l_name:'冰岛',
				r_name:'匈牙利',
				l_img:'images/flag-45.png',
				r_img:'images/flag-46.png'
			},
			{
				id:'24',
				l_name:'葡萄牙',
				r_name:'奥地利',
				l_img:'images/flag-47.png',
				r_img:'images/flag-48.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-20",
		"screenings":[
			{
				id:'25',
				l_name:'罗马尼亚',
				r_name:'阿尔巴尼亚',
				l_img:'images/flag-49.png',
				r_img:'images/flag-50.png'
			},
			{
				id:'26',
				l_name:'瑞士',
				r_name:'法国',
				l_img:'images/flag-51.png',
				r_img:'images/flag-52.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-21",
		"screenings":[
			{
				id:'27',
				l_name:'俄罗斯',
				r_name:'威尔士',
				l_img:'images/flag-53.png',
				r_img:'images/flag-54.png'
			},
			{
				id:'28',
				l_name:'斯洛伐克',
				r_name:'英格兰',
				l_img:'images/flag-55.png',
				r_img:'images/flag-56.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-22",
		"screenings":[
			{
				id:'29',
				l_name:'乌克兰',
				r_name:'波兰',
				l_img:'images/flag-57.png',
				r_img:'images/flag-58.png'
			},
			{
				id:'30',
				l_name:'北爱尔兰',
				r_name:'德国',
				l_img:'images/flag-59.png',
				r_img:'images/flag-60.png'
			},
			{
				id:'31',
				l_name:'捷克',
				r_name:'土耳其',
				l_img:'images/flag-61.png',
				r_img:'images/flag-62.png'
			},
			{
				id:'32',
				l_name:'克罗地亚',
				r_name:'西班牙',
				l_img:'images/flag-63.png',
				r_img:'images/flag-64.png'
			}
		],
		"type":1
	},
	{
		"schedule":"06-23",
		"screenings":[
			{
				id:'33',
				l_name:'冰岛',
				r_name:'奥地利',
				l_img:'images/flag-65.png',
				r_img:'images/flag-66.png'
			},
			{
				id:'34',
				l_name:'匈牙利',
				r_name:'葡萄牙',
				l_img:'images/flag-67.png',
				r_img:'images/flag-68.png'
			},
			{
				id:'35',
				l_name:'意大利',
				r_name:'爱尔兰',
				l_img:'images/flag-69.png',
				r_img:'images/flag-70.png'
			},
			{
				id:'36',
				l_name:'瑞典',
				r_name:'比利时',
				l_img:'images/flag-71.png',
				r_img:'images/flag-72.png'
			}
		],
		"type":1
	},
]
